name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  # [workflow_dispatch]

      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build image
        run: docker build -t joshuamumo/client:latest .
      - name: push image to docker hub
        run: |
         docker login -u joshuamumo -p ${{ secrets.DOCKER_HUB_TOKEN }} 
         docker push joshuamumo/client:latest
      - name: Deploy to Kubernetes
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 -d > ${HOME}/.kube/config
          cat ${HOME}/.kube/config
          
      - name: Use contecxt
        run: kubectl config use-context octobay-api
      - name: Deploy to delete and rollout deployment
        run: |
          kubectl delete pods -l app=client
          kubectl rollout status deployment/client-depl
